baseURL = "http://localhost:1313/"
languageCode = "fa-ir"
title = "My New Hugo Site"
theme = "nix"
[params]
  Name = "Mohamamd Raufzahed"
  HeaderUsername = "webdeveloper"
  HeaderHostname = "linux"
  About = "Hi! I'm Mohammad. I'm a nerd and i love developing websites and i interested in Free Software and Open Source softwares. I live in Tehran and i love it."
  ProfilePicture = "https://avatars1.githubusercontent.com/u/24861953?s=460&u=3cbd9b30dfa065657a06f50e52cd2830e11fd032&v=4"
  Email = "mohammadraufzahed@protonmail.com"
  GithubID = "your_github"
[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
