version: "3.9"

services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: personal
            POSTGRES_PASSWORD: personal
            POSTGRES_DB: personal
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    postgres_volume:
        driver: local
